### ISSUE TITLE
File.xcodeproj does not exist

### ISSUE THREAD

**Issue by ExtraBytez** [mak448a/build-ios#1]
xcodebuild: error: 'Pokemon_Battle-Mode.xcodeproj' does not exist.
Error: Process completed with exit code 66.

**Comment by ExtraBytez** [comment]
@mak448a

**Comment by ExtraBytez** [comment]
do i need to attempt to export to ios first?

**Comment by mak448a** [comment]
Yes, you first configure your iOS project in Godot. Then you export and upload to the repo.

**Comment by mak448a** [comment]
It should export a .xcodeproject and a few other files. Make sure that you've set your export location to a subfolder in your project.

**Comment by ExtraBytez** [comment]
thx
