### ISSUE TITLE
IOS be killin me

### ISSUE THREAD

**Issue by ExtraBytez** [mak448a/build-ios#3]
alright so when taking the ipa (which for some reason is only 7kb) and slapping it on the 8th gen ipad then attempting to install through trollstore it says 

```
Parse error 303
Unable to locate main binary inside of app bundle
```

**Comment by mak448a** [comment]
I replied in #2

**Comment by mak448a** [comment]
The reason why it won't run is that (most likely) it didn't build properly. So you're probably putting a partially built IPA onto your iPad.
